---
title: "Weather Changes in Geneva"
format:
  html:
    page-layout: full
    code-tools: 
      source: https://github.com/Andres-AM/weather_geneva/blob/main/weather_dashboard.qmd
server: shiny
---

```{r}
#| context: setup
#| message: false
source("libraries.R")
df <- read.table("data/climate-reports-tables-homogenized_GVE.txt",skip = 26,header = T) %>%   
  mutate( Date = as.Date(paste(Year, Month,"01",sep = "-"))) %>%
  as_tibble
```

```{r}
#| panel: fill
plotOutput('plot')
```

::: {layout-ncol="2"}
```{r}
selectInput(
  inputId = 'month_val', 
  label = 'Select the month',
  choices =  unique(month(df$Date,label = T)),
  selected = "Jan",
  multiple = F)
# numericInput(inputId = "val",label = "Grouped by :",value = 1,min = 1,max = 100,step = 1)
sliderInput(inputId = "val",label = "Grouped by :",min = 1,max = 100,value = 1,step = 1)
br()
checkboxInput('smooth', 'Smooth (see trend over the years)')
```

```{r}
DT::dataTableOutput(outputId = "table", width = "100%", height = "auto", fill = TRUE)
```

:::
```{r}
#| context: server
dataset <- reactive({
  
  df %>% 
    mutate(DatePeriod = as.Date(paste(input$val * floor(year(Date)/input$val), Month,"01",sep = "-"))) %>%
    filter( month(Date,label = T) == input$month_val) %>% 
    group_by(DatePeriod) %>% 
    summarise(Temperature  = mean(Temperature)) %>% ungroup() 

  })

output$table <- DT::renderDataTable(
  
  dataset() %>% 
    arrange(desc(DatePeriod)) %>% 
    mutate(Temperature= round(Temperature,2)) %>% 
    select(DatePeriod,Temperature) 
)

 
output$plot <- renderPlot({

  p <- dataset() %>%
    ggplot(aes(x = DatePeriod, y = Temperature )) +
    geom_line() +
    scale_x_date(date_labels = "%Y", date_breaks = "10 years") +
    labs(title  = paste0("Temperature for the month : ",input$month_val)) +
    theme(legend.position = "None")  
  
 if (input$smooth)
   p <- p + geom_smooth(se = F,method = "loess",formula = 'y ~ x')

  print(p)

})


```